### ISSUE TITLE
Downloaded and installed latest release (Version 1.2) but YOURLs' UI says 1.0

### ISSUE THREAD

**Issue by webmatros** [luixxiul/dont-log-crawlers#11]
Hey luixxiul / Suguru

First, thanks for making this plugin. Much appreciated.

A minor issue: I downloaded and installed latest release (Version 1.2) but YOURLs' plugin UI says it's version 1.0.

That's all:)
Oliver

![screen shot 2017-04-24 at 11 59 44](https://cloud.githubusercontent.com/assets/22815983/25332084/9ddf98c0-28e5-11e7-89b2-5d9c094944e8.png)

**Comment by luixxiul** [comment]
@ozh would you update the version number on your page?

**Comment by ozh** [comment]
That number displayed is generated by parsing the plugin file itself, there's nothing more to do.

When I install your plugin, I do see 1.2.......... PEBKAC.

**Comment by luixxiul** [comment]
OK I see, so closing.
