### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by BitpopCoin** [luixxiul/dont-log-crawlers#3]
'applebot',
https://support.apple.com/en-us/HT204683

'tweetedtimes',
hides that it's a bot now, Mozilla/5.0 (compatible; +http://tweetedtimes.com)

'metauri',
some verizon/nfl bot

'longurl',
LongURL API

'curl',

'ruby',

'digg',

'bot',

**Comment by luixxiul** [comment]
Thanks! Do you think it is safe to add 'curl', 'ruby' and 'bot'? They seems to me too general to be excluded.

**Comment by BitpopCoin** [comment]
Since it only affects stats, there's no safety issue I think. Depends on how small you want the database to stay.

**Comment by BitpopCoin** [comment]
Maybe add a setting for aggressive to include "bot" too

**Comment by luixxiul** [comment]
If you submit a PR for that, it would be very appriciated :smile:

**Comment by BitpopCoin** [comment]
https://github.com/luixxiul/dont-log-crawlers/pull/6

**Comment by luixxiul** [comment]
Merged. Thanks!
