### ISSUE TITLE
New crawler

### ISSUE THREAD

**Issue by James-Oakley** [luixxiul/dont-log-crawlers#7]
I just had user agent 'SubnetSearch/1.0' crawl every link on one of my sites, which bumped my yourls logs significantly. Suggest adding SubnetSearch to the array of crawlers.

**Comment by luixxiul** [comment]
Thanks @James-Oakley!

**Comment by YOzaz** [comment]
Just a note - it would be good if you'd version your plugin... otherwise we can't track if it was updated or not ;)

**Comment by luixxiul** [comment]
Thanks, @YOzaz!
